# Generated by Django 4.0.3 on 2022-04-12 06:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=1000, verbose_name='Название учереждения')),
                ('start_date', models.DateField(blank=True, verbose_name='Дата начало')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата конца')),
                ('speciality', models.CharField(max_length=500, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=1000, verbose_name='Имя компаний')),
                ('start_date', models.DateField(blank=True, verbose_name='Дата начало')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата конца')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('responsibilities', models.TextField(max_length=2000, null=True, verbose_name='Обязанности')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=300, verbose_name='Почта')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('salary', models.CharField(max_length=500, null=True, verbose_name='Желаемая зарплата')),
                ('telegram', models.CharField(max_length=300, null=True, verbose_name='Телеграмм')),
                ('facebook', models.CharField(max_length=300, null=True, verbose_name='Facebook')),
                ('category', models.CharField(choices=[('Medicine', 'Медицина'), ('Production', 'Производство'), ('Information technology', 'Информационные технологий'), ('Marketing', 'Маркетинг'), ('Sales', 'Продажи'), ('Other', 'Другое')], max_length=100, verbose_name='Категорий')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='KZ', verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='resume_pics', verbose_name='Фото')),
                ('about_me', models.TextField(max_length=5000, null=True, verbose_name='О себе')),
                ('education', models.ManyToManyField(blank=True, related_name='resum', to='headhunter.educations')),
                ('experience', models.ManyToManyField(blank=True, related_name='resume', to='headhunter.experiences')),
            ],
        ),
    ]
