# Generated by Django 4.0.3 on 2022-04-12 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='resume_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('category', models.CharField(choices=[('Medicine', 'Медицина'), ('Production', 'Производство'), ('Information technology', 'Информационные технологий'), ('Marketing', 'Маркетинг'), ('Sales', 'Продажи'), ('Other', 'Другое')], max_length=100, verbose_name='Категория')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание вакансии')),
                ('min_years_experience', models.IntegerField(verbose_name='Мин кол-во лет опыта')),
                ('max_years_experience', models.IntegerField(verbose_name='Макс кол-во лет опыта')),
                ('posted_status', models.BooleanField(verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespondMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_text', to='headhunter.message')),
                ('respond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_message', to='headhunter.respond')),
            ],
        ),
        migrations.AddField(
            model_name='respond',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_resume', to='headhunter.resume'),
        ),
        migrations.AddField(
            model_name='respond',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_vacancy', to='headhunter.vacancy'),
        ),
        migrations.AddField(
            model_name='respond',
            name='vacancy_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
