# Generated by Django 4.0.3 on 2022-04-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0002_message_respond_resume_user_vacancy_respondmessage_and_more'),
        ('headhunter', '0002_resume_user'),
    ]

    operations = [
    ]
