# Generated by Django 4.0.3 on 2022-04-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0003_merge_20220415_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='user',
            new_name='author',
        ),
    ]
