# Generated by Django 4.0.3 on 2022-04-12 17:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headhunter', '0003_merge_20220412_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1', max_length=128, region='KZ', verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='resume',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Публикация резюме'),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.ManyToManyField(blank=True, related_name='resume_experience', to='headhunter.experiences'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.CharField(choices=[('Medicine', 'Медицина'), ('Production', 'Производство'), ('Information technology', 'Информационные технологий'), ('Marketing', 'Маркетинг'), ('Sales', 'Продажи'), ('Other', 'Другое')], max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='resume_education', to='headhunter.educations'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='telegram',
            field=models.URLField(default='1', max_length=500, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
