# Generated by Django 4.0.3 on 2022-04-12 17:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0004_remove_resume_about_me_remove_resume_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='telegram',
            field=models.URLField(max_length=500, verbose_name='Telegram'),
        ),
    ]
