# Generated by Django 4.0.3 on 2022-04-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0005_alter_resume_phone_number_alter_resume_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(max_length=2000, null=True, verbose_name='Об о мне'),
        ),
    ]
