# Generated by Django 4.0.3 on 2022-04-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0005_alter_vacancy_max_years_experience_and_more'),
        ('headhunter', '0006_resume_about_me'),
    ]

    operations = [
    ]
