# Generated by Django 4.0.3 on 2022-04-11 10:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='8 777 777 77 77', max_length=128, region='KZ', unique=True, verbose_name='Номер телефона'),
        ),
    ]
