# Generated by Django 4.0.3 on 2022-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_or_company',
            field=models.BooleanField(default=True, verbose_name='Соискатель'),
        ),
    ]
