# Generated by Django 4.0.3 on 2022-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_or_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_or_company',
            field=models.BooleanField(default=False, verbose_name='Соискатель'),
        ),
    ]
