# Generated by Django 4.0.3 on 2022-04-11 14:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_or_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', unique=True, verbose_name='Номер телефона'),
        ),
    ]
